name: theo
favicon: null
layout_spectrum: 0.7828031827230006
typography_spectrum: 0.1262772234622389
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4856558234896511
  lightness: 0.16195739363320172
  saturation: 0.5717775947414339
  rhythmicContrast: 0.1325550014153123
purpose: []
